dependencies {
    api project(":core")

    compileOnly "com.fasterxml.jackson.core:jackson-databind:2.22.2"
    compileOnly "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.22.2"

    testImplementation "com.fasterxml.jackson.core:jackson-databind:2.22.2"
    testImplementation "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.22.2"
}
